name       : thermald
version    : '2.5'
release    : 11
source     :
    - https://github.com/intel/thermal_daemon/archive/refs/tags/v2.5.tar.gz : e6515678ce8ff37978a453e1617a087a40ba3a31809a42c1768b6f816e564cc9
license    : GPL-2.0-or-later
homepage   : https://github.com/intel/thermal_daemon
component  : system.utils
summary    : Thermal daemon for IA
description: |
    Thermal daemon for IA
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(libevdev)
    - pkgconfig(libxml-2.0)
    - pkgconfig(upower-glib)
    - autoconf-archive
    - gtk-doc
setup      : |
    %autogen --with-dbus-sys-dir=/usr/share/dbus-1/system.d/
build      : |
    %make
install    : |
    %make_install

    # Users may systemctl mask to turn it off.
    install -d -D -m 00755 $installdir/%libdir%/systemd/system/multi-user.target.wants
    ln -sv thermald.service $installdir/%libdir%/systemd/system/dbus-org.freedesktop.thermald.service
    ln -sv ../thermald.service $installdir/%libdir%/systemd/system/multi-user.target.wants
