name       : thermald
version    : 2.1.0
release    : 7
source     :
    - https://github.com/intel/thermal_daemon/archive/v2.1.tar.gz : 4ad17a747a72912a46cf59d4451fb07a56a7f7e4713ed3fa217e97275b35dfde
license    : GPL-2.0-or-later
component  : system.utils
summary    : Thermal daemon for IA
description: |
    Thermal daemon for IA
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gio-unix-2.0)
    - pkgconfig(libxml-2.0)
    - autoconf-archive
setup      : |
    %patch -p1 < $pkgfiles/0001-Do-not-start-on-virtualized-environments.patch
    %autogen
build      : |
    %make
install    : |
    %make_install

    # We use systemd.
    rm -rf $installdir/etc/init

    # Users may systemctl mask to turn it off.
    install -d -D -m 00755 $installdir/%libdir%/systemd/system/multi-user.target.wants
    ln -sv thermald.service $installdir/%libdir%/systemd/system/dbus-org.freedesktop.thermald.service
    ln -sv ../thermald.service $installdir/%libdir%/systemd/system/multi-user.target.wants
