name       : thermald
version    : 1.5.3
release    : 2
source     :
    - https://github.com/01org/thermal_daemon/archive/v1.5.3.tar.gz : e20b450ef27a5b5e45474c831663c8f5ecd14c82ace5a4b1e06c442e0a23b53e
license    : GPL-2.0
component  : system.utils
summary    : Thermal daemon for IA
description: |
    Thermal daemon for IA
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(gio-unix-2.0)
    - pkgconfig(libxml-2.0)
setup      : |
    %patch -p1 < $pkgfiles/0001-Do-not-start-on-virtualized-environments.patch
    %autogen
build      : |
    %make
install    : |
    %make_install

    # We use systemd.
    rm -rf $installdir/etc/init

    # Users may systemctl mask to turn it off.
    install -d -D -m 00755 $installdir/%libdir%/systemd/system/multi-user.target.wants
    ln -sv ../thermald.service $installdir/%libdir%/systemd/system/dbus-org.freedesktop.thermald.service
    ln -sv ../thermald.service $installdir/%libdir%/systemd/system/multi-user.target.wants
