name       : thermald
version    : '1.8'
release    : 6
source     :
    - https://github.com/intel/thermal_daemon/archive/v1.8.tar.gz : 662456eff5b7ee5a42e54b8a667d002d3a4dec5cacbddc5e1ab5ec94dab218c6
license    : GPL-2.0-or-later
component  : system.utils
summary    : Thermal daemon for IA
description: |
    Thermal daemon for IA
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gio-unix-2.0)
    - pkgconfig(libxml-2.0)
setup      : |
    %patch -p1 < $pkgfiles/0001-Do-not-start-on-virtualized-environments.patch
    %autogen
build      : |
    %make
install    : |
    %make_install

    # We use systemd.
    rm -rf $installdir/etc/init

    # Users may systemctl mask to turn it off.
    install -d -D -m 00755 $installdir/%libdir%/systemd/system/multi-user.target.wants
    ln -sv thermald.service $installdir/%libdir%/systemd/system/dbus-org.freedesktop.thermald.service
    ln -sv ../thermald.service $installdir/%libdir%/systemd/system/multi-user.target.wants
