name       : thermald
version    : 1.6
release    : 3
source     :
    - https://github.com/01org/thermal_daemon/archive/v1.6.tar.gz : c63ae1b031f2b4ce037441e7e9910d05405b540fe6668e156d32c56d5dfa7492
license    : GPL-2.0
component  : system.utils
summary    : Thermal daemon for IA
description: |
    Thermal daemon for IA
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gio-unix-2.0)
    - pkgconfig(libxml-2.0)
setup      : |
    %patch -p1 < $pkgfiles/0001-Do-not-start-on-virtualized-environments.patch
    %autogen
build      : |
    %make
install    : |
    %make_install

    # We use systemd.
    rm -rf $installdir/etc/init

    # Users may systemctl mask to turn it off.
    install -d -D -m 00755 $installdir/%libdir%/systemd/system/multi-user.target.wants
    ln -sv thermald.service $installdir/%libdir%/systemd/system/dbus-org.freedesktop.thermald.service
    ln -sv ../thermald.service $installdir/%libdir%/systemd/system/multi-user.target.wants
